import { createComponent } from "@ui5/webcomponents-base/dist/createComponent.js";
import { useRef, useState, useCallback, useEffect } from "react";
import ButtonClass from "@ui5/webcomponents/dist/Button.js";
import CheckBoxClass from "@ui5/webcomponents/dist/CheckBox.js";
import DialogClass from "@ui5/webcomponents/dist/Dialog.js";
import IconClass from "@ui5/webcomponents/dist/Icon.js";
import LinkClass from "@ui5/webcomponents/dist/Link.js";
import PanelClass from "@ui5/webcomponents/dist/Panel.js";
import TextClass from "@ui5/webcomponents/dist/Text.js";
import TitleClass from "@ui5/webcomponents/dist/Title.js";

const Button = createComponent(ButtonClass);
const CheckBox = createComponent(CheckBoxClass);
const Dialog = createComponent(DialogClass);
const Icon = createComponent(IconClass);
const Link = createComponent(LinkClass);
const Panel = createComponent(PanelClass);
const Text = createComponent(TextClass);
const Title = createComponent(TitleClass);

function App() {
  const dialogRef = useRef(null);
  const checkboxRef = useRef(null);
  const [acceptDisabled, setAcceptDisabled] = useState(true);
  const hasScrolledToBottomRef = useRef(false);

  useEffect(() => {
    if (dialogRef.current) {
      dialogRef.current!.open = true;
    }
  }, []);

  const handleAcceptButtonClick = useCallback((e: Event) => {
    const checkbox = checkboxRef.current;
    if (!hasScrolledToBottomRef.current || !checkbox?.checked) {
      e.preventDefault();
    }
  }, []);

  const handleCheckboxMousedown = useCallback((e: MouseEvent) => {
    if (!hasScrolledToBottomRef.current) {
      e.preventDefault();
    }
  }, []);

  const handleCheckboxChange = useCallback(() => {
    const checkbox = checkboxRef.current;
    setAcceptDisabled(!(hasScrolledToBottomRef.current && checkbox?.checked));
  }, []);

  const handleTermsPanelScroll = useCallback((e: Event) => {
    const panel = e.currentTarget;
    const scrollTop = panel.scrollTop;
    const clientHeight = panel.clientHeight;
    const scrollHeight = panel.scrollHeight;
    const atBottom = scrollTop + clientHeight >= scrollHeight - 1;

    if (atBottom) {
      hasScrolledToBottomRef.current = true;
      const checkbox = checkboxRef.current;
      setAcceptDisabled(!checkbox?.checked);
    }
  }, []);

  return (
    <>
      <style>{`
        body {
        	background-color: var(--sapBackgroundColor);
        	height: 800px;
        }

        [ui5-panel]::part(content) {
        	background-color: #eaecee;
        }

        .checkbox-wrapper {
        	display: flex;
        	align-items: center;
        }

        .checkbox-wrapper [ui5-text] {
        	flex: 1;
        }

        #termsPanel {
        	max-height: 400px;
        	overflow: auto;
        	border: 1px dashed #000;
        	border-radius: 0.25rem;
        	background-color: #eaecee;
        }

        .text {
        	padding-top: 0.15rem;
        	padding-bottom: 0.15rem;
        }

        .footer {
        	display: flex;
        	justify-content: flex-end;
        	width: 100%;
        	align-items: center;
        	gap: 0.25rem;
        }

        [ui5-icon] {
            color: var(--sapInformativeElementColor);
        	vertical-align: middle;
        	margin-left: 0.1rem;
        	margin-right: 0.1rem;
        	width: 0.8rem;
        	height: 0.8rem;
        }
      `}</style>
      <Dialog
        ref={dialogRef}
        id="dialog"
        state="Information"
        headerText="Information"
      >
        <br />
        <Text>
          Please read the following information carefully and accept these terms
          and conditions:
        </Text>
        <br />
        <Title level="H5">Terms of use</Title>
        <br />
        <Panel
          id="termsPanel"
          expanded={true}
          onScroll={handleTermsPanelScroll}
        >
          <Text class="text">
            <strong>SAP AI TERMS</strong>
          </Text>
          <Text class="text">
            These SAP AI Terms (&quot;Terms&quot;) apply to artificial
            intelligence features and technologies provided with SAP
          </Text>
          <Text class="text">
            Cloud Services (&quot;AI Technology&quot;). &quot;Output&quot; means
            any content generated by AI Technology as output,
          </Text>
          <Text class="text">
            based on the data provided to AI Technology, including Customer
            Data, and data used to train AI
          </Text>
          <Text class="text">Technology.</Text>
          <Text class="text">
            1. <strong>ACCEPTABLE USE</strong>
          </Text>
          <Text class="text">
            1.1. Customer will use AI Technology responsibly, safely, in a
            legally compliant manner, and in accordance
          </Text>
          <Text class="text">
            with the Documentation, and will not use AI Technology to:
          </Text>
          <Text class="text">
            (a) Promote or facilitate illegal activities or unlawful actions;
          </Text>
          <Text class="text">(b) Facilitate fraudulent actions;</Text>
          <Text class="text">
            (c) Attempt unauthorized access to a system, property, or
            information;
          </Text>
          <Text class="text">
            (d) Generate content that contains or promotes violence, hate
            speech, or harassment, or insults or
          </Text>
          <Text class="text">demeans a person;</Text>
          <Text class="text">(e) Generate sexually explicit content;</Text>
          <Text class="text">(f) Distribute malware or spam;</Text>
          <Text class="text">(g) Contravene regulatory safety policies;</Text>
          <Text class="text">(h) Track people without consent;</Text>
          <Text class="text">(i) Falsely impersonate an individual; or</Text>
          <Text class="text">(j) Mine cryptocurrency.</Text>
          <Text class="text">
            1.2. SAP may limit or suspend access to Output or AI Technology in
            the event these Terms are violated or for
          </Text>
          <Text class="text">non-compliance with Documentation.</Text>
          <Text class="text">
            1.3. Customer will not circumvent or bypass protective measures made
            available by SAP or a third-party,
          </Text>
          <Text class="text">
            including, but not limited to, those intended to help prevent
            copyright infringement, data breaches, or
          </Text>
          <Text class="text">security incidents.</Text>
          <Text class="text">
            1.4. Customer will not{" "}
            <Icon name="information" accessibleName="Info" title="More info" />{" "}
            use AI Technology or Output to develop, train, or improve other AI
            services or AI
          </Text>
          <Text class="text">
            models, unless explicitly permitted by SAP, or (ii) use web
            scraping, web harvesting, or web data extraction
          </Text>
          <Text class="text">
            methods to extract data from AI Technology or Output.
          </Text>
          <Text class="text">
            2. <strong>OUTPUT</strong>
          </Text>
          <Text class="text">
            2.1. Notwithstanding any recommendation contained within Output,
            reliance on Output is in Customer's
          </Text>
          <Text class="text">
            discretion. Customer will assess Output (including by code scanning,
            security scanning, human review,
          </Text>
          <Text class="text">
            and human oversight and correction) before using or relying on the
            Output for any purpose. Customer will
          </Text>
          <Text class="text">
            also utilize any review tools and filtering options that SAP makes
            available.
          </Text>
          <Text class="text">
            2.2. AI Technology consists of emerging technologies and, given the
            nature of such technologies, their use
          </Text>
          <Text class="text">
            may result in incorrect, biased, unfair, or inaccurate Output and/or
            Output that may be nonsensical or
          </Text>
          <Text class="text">untruthful in relation to certain sources.</Text>
          <Text class="text">
            2.3. In addition Output may not qualify for intellectual property
            protection; similar or the same Output may be
          </Text>
          <Text class="text">
            produced by AI Technology to similar requests from different
            customers, and Customer's rights to Output
          </Text>
          <Text class="text">
            may not be enforceable against other users of AI Technology.
            Customer's ownership in Output is subject
          </Text>
          <Text class="text">
            to SAP's and/or its licensor's ownership rights in the Cloud
            Service, SAP Materials, and data used to train
          </Text>
          <Text class="text">
            AI Technology (&quot;Pre-Existing Materials&quot;). Customer is
            granted a right to use, and only will use, Pre-
          </Text>
          <Text class="text">
            Existing Materials in Output to the same extent as Customer is
            permitted to use the Cloud Service.
          </Text>
          <Text class="text">
            3. <strong>ADDITIONAL TERMS</strong>
          </Text>
          <Text class="text">
            The legal framework applicable to and the interpretation of
            competent courts and authorities regarding the
          </Text>
          <Text class="text">
            use of AI technologies is evolving. If a change in law or the
            interpretation of a competent court or authority
          </Text>
          <Text class="text">
            results in{" "}
            <Icon name="information" accessibleName="Info" title="More info" />{" "}
            SAP's inability to offer an AI Technology or (ii) Customer's
            inability to use an AI Technology
          </Text>
          <Text class="text">
            in a legally compliant manner, SAP may reduce the scope of use
            (e.g., if the use of an AI Technology
          </Text>
          <Text class="text">
            becomes prohibited, SAP may cease offering such AI Technology in a
            given country ) or remove such AI
          </Text>
          <Text class="text">
            Technology altogether. The same applies where SAP can no longer
            provide an AI Technology provided
          </Text>
          <Text class="text">
            by a third-party, because such third-party discontinues availability
            of such AI Technology or changes its
          </Text>
          <br />
          <br />
          <br />
          <Text class="text">SAP AI Terms enMEE.v.10-2024 Page 2 of 2</Text>
          <Text class="text">
            service terms or documentation in contradiction to the Agreement or
            another way that prevents SAP from
          </Text>
          <Text class="text">further offering such AI Technology.</Text>
          <Text class="text">
            3.2. AI Technology may include AI models, technologies or features
            licensed from third-parties that require
          </Text>
          <Text class="text">
            SAP to pass through additional terms. Customer will comply with such
            pass-through terms as made
          </Text>
          <Text class="text">
            available by SAP at
            https://www.sap.com/about/trust-center/agreements.html, within the
            Documentation,
          </Text>
          <Text class="text">
            or otherwise. When SAP introduces new AI Technology, SAP may provide
            additional terms or make
          </Text>
          <Text class="text">
            updates to the terms, that apply to Customer's use of such AI
            Technology.
          </Text>
          <Text class="text">
            3.3. SAP does not commit to the use of specific AI models in a Cloud
            Service even if Customer may be able
          </Text>
          <Text class="text">
            to choose between different AI models when using the Cloud Service.
            SAP reserves the right to add,
          </Text>
          <Text class="text">
            remove, or exchange AI models, in its sole discretion, at any time.
          </Text>
        </Panel>
        <br />
        <div className="checkbox-wrapper">
          <CheckBox
            ref={checkboxRef}
            id="termsCheck"
            onMouseDown={handleCheckboxMousedown}
            onChange={handleCheckboxChange}
          />
          <Text>
            I hereby confirm I have read and agreed to
            <Link href="https://www.sap.com" target="_blank">
              &lt;document link 1&gt;
            </Link>{" "}
            and
            <Link href="https://www.sap.com" target="_blank">
              &lt;document link 2&gt;
            </Link>
            .
          </Text>
        </div>
        <br />
        <div slot="footer" className="footer">
          <Button
            design="Emphasized"
            id="acceptButton"
            disabled={acceptDisabled}
            onClick={handleAcceptButtonClick}
          >
            Accept
          </Button>
          <Button>Dismiss</Button>
        </div>
      </Dialog>
    </>
  );
}

export default App;
